### ISSUE TITLE
Why the extension is missing in the vscode marketplace?

### ISSUE THREAD

**Issue by GideonWolfe** [dlasagno/vscode-wal-theme#10]
I'm not sure what I'm doing wrong, as entering the command in the directions gives me search results, which does not include this theme.

![image](https://user-images.githubusercontent.com/32942052/95301459-7ee29700-0835-11eb-976c-9c65e0e62e62.png)

**Comment by dlasagno** [comment]
I'm not sure what's happening, this probably should be issued to vscode repository since I'm not responsible for the search results.
That said, I could suggest that you check that your vscode is up to date.
You can also try to install it from the [official marketplace page](https://marketplace.visualstudio.com/items?itemName=dlasagno.wal-theme). On that page you can also find the download link of the `.vsix` file that you can install manually with this command: `code --install-extension path/to/extension.vsix`.

**Comment by GideonWolfe** [comment]
I ran `code /path/to/extension.vsix` and this is what I get.

![image](https://user-images.githubusercontent.com/32942052/95368543-1e7e4480-088b-11eb-80be-1c250eff348a.png)

It just tries to open the file, not install it.

**Comment by lakosd** [comment]
If you're using VSCodium this extension is not included in its marketplace. However, you can add all VSCode extensions to VSCodium as seen here: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by GideonWolfe** [comment]
I'm just using `code` from the Arch repos. I definitely didn't have issues installing this on my last system but the extension simply isn't showing up in the marketplace for me. Plenty of others are...

I can manually "Install from VSIX" though.

**Comment by dlasagno** [comment]
I checked the command for installing extensions manually, actually it is: 
```
code --install-extension path/to/extension.vsix
```
I will also update the first message that I sent to make sure who comes here can find the correct command.
Still, I think that, if you continue to have this problem, the vscode repo is the best place to get help.
