### ISSUE TITLE
Would be cool being able to tell VSCode if the theme is light

### ISSUE THREAD

**Issue by arudp** [dlasagno/vscode-wal-theme#12]
So `wal` has the `-l` flag to tell it it's a light theme. But this is not the thing we might want to rely on! If someone uses the `-f` flag to use a file, you end up not having that info.

What I'm trying to say is, it would be nice that `"type": "dark",` in the `wal*.json` files wasn't hardcoded but calculated using, maybe the background to say "it's light" or "it's dark".

Of course I don't know if this might even be possible, but I wanted to ask :slightly_smiling_face: 

Keep up the great work! :grin:

**Comment by dlasagno** [comment]
I see your point, I even thought of it myself. Unfortunately that is not possible: the type of theme(light or dark) is set from the package.json, a file that is not supposed the change in time. Updating that file is not recommended and probably you'll end up seeing the changes only the next time the extension is loaded.
Also, it could be confusing for the user: one might expect to find the theme always in the same place.
I ended up choosing dark because that is was most people  have.

Edit: I'm not really sure of what the type entry in the wal*.json file does, I'll take a further look in to it but I haven't been able to find it in documentation.

**Comment by arudp** [comment]
Ah, such a shame! :slightly_smiling_face: 
I usually switch from light to dark and viceversa depending on my environment (one of the reasons I rely on pywal, makes it easy to have one source of truth for my themes) and alas, I have [this bit of CSS](https://github.com/arudp/markdownForVSCode/blob/main/markdown.css) for Markdown in VSCode but I'm guessing this relies on the `type` for the `vscode-light` or `vscode-dark` classes.

Aside from that... I think the other reason for `type` is to get them separated in the _Choose theme_ selector and for filtering extensions.

**Comment by dlasagno** [comment]
I tried changing `type`, but in the end, nothing changed: wal theme is still in the dark section.
I couldn't figure out what that entry actually does, so I'll leave it as it is for the time being.
I'll take a look back into this when vscode will officially support dynamic themes.
