### ISSUE TITLE
EROFS: read-only file system

### ISSUE THREAD

**Issue by rourke** [dlasagno/vscode-wal-theme#26]
I'm running NixOS which is using a read-only file system. I have the extension installed but whenever I change my wallpaper through `wal`, the extension returns the following error:

```
EROFS: read-only file system, open '/nix/store/vh8ikilblbcvga2l002254177dg5g9xg-vscode-extension-dlasagno-wal-theme-1.2.0/share/vscode/extensions/dlasagno.wal-theme/themes/wal.json'
```

I assume it wants to write the color settings to this file? Is it possible to point this towards a location in the user directory? Maybe point it to a wal generated template?

**Comment by dlasagno** [comment]
Unfortunately the extension needs to write on the disk in order to create the theme based on the colors provided by wal. The exact location is inside the extension folder. You could install vscode locally(on the user) instead of installing it on the system to fix your problem. I can't get the theme file externally, the whole point of the extension is to generate it for you, otherwise you could simply create your own theme.

**Comment by blaze-developer** [comment]
> I'm running NixOS which is using a read-only file system. I have the extension installed but whenever I change my wallpaper through `wal`, the extension returns the following error:
> 
> ```
> EROFS: read-only file system, open '/nix/store/vh8ikilblbcvga2l002254177dg5g9xg-vscode-extension-dlasagno-wal-theme-1.2.0/share/vscode/extensions/dlasagno.wal-theme/themes/wal.json'
> ```
> 
> I assume it wants to write the color settings to this file? Is it possible to point this towards a location in the user directory? Maybe point it to a wal generated template?

Did you ever find a workaround to this issue? I don't think simply installing on a user will suffice, as all programs on NixOS are installed in the nix store.

I apologize for the necropost, but this is the only place I could find any information about this issue after searching.

**Comment by blaze-developer** [comment]
> Unfortunately the extension needs to write on the disk in order to create the theme based on the colors provided by wal. The exact location is inside the extension folder. You could install vscode locally(on the user) instead of installing it on the system to fix your problem. I can't get the theme file externally, the whole point of the extension is to generate it for you, otherwise you could simply create your own theme.

By locally, do you mean imperatively through the extension marketplace? If that is the only way to get this working, its unfortunate we cannot install this extension declaratively :(

**Comment by dlasagno** [comment]
> > Unfortunately the extension needs to write on the disk in order to create the theme based on the colors provided by wal. The exact location is inside the extension folder. You could install vscode locally(on the user) instead of installing it on the system to fix your problem. I can't get the theme file externally, the whole point of the extension is to generate it for you, otherwise you could simply create your own theme.
> 
> By locally, do you mean imperatively through the extension marketplace? If that is the only way to get this working, its unfortunate we cannot install this extension declaratively :(

Basically vscode looks in the extension folder for the json file containing the theme, and loads it. Since this theme is "dynamic", the extension needs to regenerate the json file of the theme with the new set of colors. All the other themes you find in the vscode marketplace use a static json file, that's why they don't require write permission. 

Maybe a symlink could do the trick, but even then the extension has to write the json file somewhere.

**Comment by nekotori55** [comment]
What about writing theme file to a XDG state folder? Idk if this is possible, but if it is, I think this would be a good way to solve the issue

**Comment by dlasagno** [comment]
Sorry for the late reply, the path of the file is specified in a static json file that vscode picks up. There's no option to set it dynamically, and so, I can't rely on a path outside the extension folder, otherwise it may break for other users.
