### ISSUE TITLE
how to install this in VSCodium

### ISSUE THREAD

**Issue by prankousky** [dlasagno/vscode-wal-theme#8]
Hi,

I stumbled upon this extension. Is it possible to install in `VSCodium` as well, and if so, how can I do it? Thank you in advance for your support :)

**Comment by dlasagno** [comment]
I never used VSCodium(I use code-oss), but I looked at the github page and it seems that you can simply download the extension from the marketplace. I can't guarantee that the extension will work because it relies on an unofficial feature, but I think that it should work anyway. Try to install it and follow the instructions on the extension page, and let me know if it doesn't work.
